sudo: false
language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=flake8
  - TOXENV=docs
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
branches:
  only:
    - master
